### ISSUE TITLE
AttributeError: 'int' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by pawel125** [fls-bioinformatics-core/GFFUtils#10]
Hi! I have some trouble with running cleaning phase. Here is the output:

GFFcleaner 0.10.1
Input : GCF_000001635.26_GRCm38.p6_genomic.1.gff
Output: GCF_000001635.26_GRCm38.p6_genomic.1_clean.gff
Replacing 'Anc_*' and blanks with '0's in 'score' column
Traceback (most recent call last):
  File "GFFcleaner", line 10, in <module>
    sys.exit(main())
  File "python2.7/site-packages/GFFUtils/GFFcleaner.py", line 718, in main
    if data['score'].startswith('Anc_') or data['score'].strip() == '':
AttributeError: 'int' object has no attribute 'startswith'
srun: error: wn114: task 0: Exited with exit code 1

Can you tell me what does it mean and how to fix it?
Thank you!

**Comment by pjbriggs** [comment]
Hello @pawel125 

Sorry you've encountered a problem with `GFFcleaner`.

I've managed to reproduce the error you report by running the program using the `--clean-score` option, and putting an integer value into the `score` column of the input GFF. But I think the error will affect most files unless the `score` is blank, a string starting with `Anc_`, or is zero.

There is a fix in pull request #11 which I'll use to make a new release of the package. I'll update this issue when the new version is available (later today).

**Comment by pjbriggs** [comment]
@pawel125 I've now made release 0.10.2 of the code. Could you reinstall and let me know if this fixes the error for you? Thanks.

**Comment by pawel125** [comment]
I have reinstalled it and run again. This is the end of the output:

...
WARNING: No value for 'SGD' ('Parent')
WARNING: No value for 'SGD' ('ID')
WARNING: No value for 'SGD' ('ID')
WARNING: No value for 'SGD' ('ID')
WARNING: No value for 'SGD' ('ID')
WARNING: No value for 'SGD' ('ID')
WARNING: No value for 'SGD' ('ID')
Excluding keys:
        kaks
        kaks2
        ncbi
Grouping SGDs by setting ID's for consecutive lines with the same SGD values
Traceback (most recent call last):
  File "envs\py27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "envs\py27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "envs\py27\Scripts\GFFcleaner.exe\__main__.py", line 9, in <module>
  File "envs\py27\lib\site-packages\GFFUtils\GFFcleaner.py", line 762, in main
    GFFGroupSGDs(gff_data)
  File "envs\py27\lib\site-packages\GFFUtils\GFFcleaner.py", line 355, in GFFGroupSGDs
    sgd = attributes['SGD']
  File "envs\py27\lib\site-packages\GFFUtils\GFFFile.py", line 229, in __getitem__
    raise KeyError
KeyError


so it still doesn't work properly. This is the gff file that I use:
ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Mus_musculus/latest_assembly_versions/GCF_000001635.26_GRCm38.p6/GCF_000001635.26_GRCm38.p6_genomic.gff.gz

**Comment by pjbriggs** [comment]
Hello @pawel125 sorry you're still having problems.

Can you also provide the command line that you're using so that I can confirm which options are being used? Thanks!

**Comment by pawel125** [comment]
Sure!
> GFFcleaner --clean GCF_000001635.26_GRCm38.p6_genomic.gff

**Comment by pjbriggs** [comment]
Thanks @pawel125 I've now made release 0.10.3 of the code, which works okay for me on that file and using that command line. Can you let me know whether it works for you now?

**Comment by pawel125** [comment]
@pjbriggs, now it works, although I can not see any difference between original and cleaned files. Maybe it was clean enough.
Thanks!

**Comment by pjbriggs** [comment]
@pawel125 thanks for letting me know.
