### ISSUE TITLE
Upgrade to Python 3.x

### ISSUE THREAD

**Issue by raivivek** [fls-bioinformatics-core/GFFUtils#13]
Python 2.7 has been retired and doesn't receive any support. It would be good to have Python 3.x support for continued future use. Thanks!

**Comment by pjbriggs** [comment]
Hello @raivivek 

I didn't originally plan to port this package over to Python 3 as it's pretty old. But it looks like it's still useful from time to time, so I'm looking into doing this now.

I'll update this issue when I've got something working.

Peter

**Comment by raivivek** [comment]
I'd be happy to help with any specific issues

**Comment by pjbriggs** [comment]
Hello @raivivek 

Just to let you know: the `devel` branch now contains updates to the code that should enable it work under Python 3.7. So if you need to have the package running under Python 3 then you could try these updates and see if they work for you - if so then please let me know if there are any problems. (This isn't a priority for me right now but I will endeavor to deal with anything that comes up as soon as I'm able.)

When I get a chance to tidy things up and do a bit more testing then I'll make a new release with official Python 3 support.

Peter

**Comment by raivivek** [comment]
Hi @pjbriggs Thanks for all the work. I get an error about dependency `genomics-bcftbx` when trying to install from devel.
```
pip install git+https://github.com/fls-bioinformatics-core/GFFUtils@devel
Collecting git+https://github.com/fls-bioinformatics-core/GFFUtils@devel
  Cloning https://github.com/fls-bioinformatics-core/GFFUtils (to revision devel) to /localscratch/vivekrai/pip-req-build-rh6w8y_q
  Running command git clone -q https://github.com/fls-bioinformatics-core/GFFUtils /localscratch/vivekrai/pip-req-build-rh6w8y_q
  Running command git checkout -b devel --track origin/devel
  Switched to a new branch 'devel'
  Branch devel set up to track remote branch devel from origin by rebasing.
Requirement already satisfied (use --upgrade to upgrade): GFFUtils==0.10.3 from git+https://github.com/fls-bioinformatics-core/GFFUtils@devel in ./.anaconda3/lib/python3.7/site-packages/GFFUtils-0.10.3-py3.7.egg
Collecting genomics-bcftbx (from GFFUtils==0.10.3)
  ERROR: Could not find a version that satisfies the requirement genomics-bcftbx (from GFFUtils==0.10.3) (from versions: none)
ERROR: No matching distribution found for genomics-bcftbx (from GFFUtils==0.10.3)
```

**Comment by pjbriggs** [comment]
Hello @raivivek 

Thanks for giving this a try. The problems sound quite similar to those encountered in issue #14 for the Python2 installation.

First: I'd recommend trying the install into a Python virtualenv, rather than directly into the system. Virtualenvs tend to make dependency management much more straightforward.

Then: before attempting to install `GFFUtils`, you need to install the requirements using the `requirements.txt` file, e.g.

    pip install -r https://raw.githubusercontent.com/fls-bioinformatics-core/GFFUtils/devel/requirements.txt

Please let me know if you've tried these things and are still seeing an error.

Peter

**Comment by raivivek** [comment]
Thanks! I was able to install it and check basic CLI functionality. At this point, I'm wondering if the tools/scripts in this package have a more consistent naming scheme. You could either choose `GTFXXX` or `gtf_xxx` or something. It'd make it easier for users to locate commands.

Finally, we could also run a code formatter (such as black) to tidy up the code (not that anything's wrong with it, just more consistent). Thanks for all the work.
