### ISSUE TITLE
add copy header to produce a valid GFF with GTF_extract 

### ISSUE THREAD

**Issue by splaisan** [fls-bioinformatics-core/GFFUtils#2]
I now tried it and had to copy the header from the input before adding the command data

```
grep "^#" input.gff3 | grep -v "^###" > genes.gff3
GTF_extract -f gene input.gff3 --gff >> genes.gff3
```

also, the -o option did not seem to save and I had to use the redirect instead
Thanks for the great tool

**Comment by pjbriggs** [comment]
Hello @splaisan 

Thanks for the bug report and feature request - I've fixed the `-o` option and added a new `-k` option to copy the header from the input file. Both these changes are in the latest version of `GFFUtils` (v0.10.0).

Thanks for your interest in `GFFUtils`!
