### ISSUE TITLE
problem with python 3.4

### ISSUE THREAD

**Issue by didiercroes** [fls-bioinformatics-core/GFFUtils#3]
Hi,
I have a issue with python 3.4:
Traceback (most recent call last):
  File "/usr/bin/GFF3_Annotation_Extractor", line 7, in <module>
    from GFFUtils.GFF3_Annotation_Extractor import main
  File "/usr/lib/python3.4/site-packages/GFFUtils/GFF3_Annotation_Extractor.py", line 87
    print "Input file is '%s' format" % self.__feature_data_format
can you help me?

Thanks

Didier

**Comment by didiercroes** [comment]
Forgot this line:

SyntaxError: Missing parentheses in call to 'print'

**Comment by pjbriggs** [comment]
Hello @didiercroes 

Thanks for the feedback - unfortunately `GFFUtils` is currently only compatible with Python2 at the moment and I'm not able to say when or if I'll be able to port it to Python3.

So for the time being I'd recommend using the software with Python2.

Thanks for your interest in `GFFUtils`!

**Comment by Kador-phd** [comment]
Yep,
I saw and corrected the problem. Maybe it could be good idea to change the installation instructions from "pip" to "pip2" or "pip2.7"
Thanks for you help
kind regards

Didier

**Comment by pjbriggs** [comment]
@didiercroes @Kador-phd I've updated the documentation as per your suggestion. Also I've added a keyword to the `setup.py` file which will refuse to install on Python 3 (provided the user has `pip` version 9 or higher). Hopefully these changes will address your concerns.

Thanks for your interest in `GFFUtils`.
