### ISSUE TITLE
install link to requirements.txt broken

### ISSUE THREAD

**Issue by estolle** [fls-bioinformatics-core/GFFUtils#8]
Hi

The instruction says "pip2 install https://raw.githubusercontent.com/fls-bioinformatics-core/GFFUtils/refactor/requirements.txt" to install GFFUtils, However, that link is broken.

For me it works to change it to the following 2:
sudo -H pip install -r https://github.com/fls-bioinformatics-core/GFFUtils/blob/master/requirements.txt
sudo -H pip install -r https://raw.githubusercontent.com/fls-bioinformatics-core/GFFUtils/master

**Comment by pjbriggs** [comment]
Hello @estolle thanks for reporting this - I've now updated the link in the documentation to one that works.

Thanks for your interest in `GFFUtils`!
